apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  labels:
    app: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
      - name: apm-server
        image: node:22-alpine
        ports:
        - containerPort: 9009
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  labels:
    app: apm-server
spec:
  selector:
    app: apm-server
  ports:
  - name: port-9009
    port: 9009
    targetPort: 9009
    protocol: TCP
  type: ClusterIP
