apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-core
  labels:
    app: cpp-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-core
  template:
    metadata:
      labels:
        app: cpp-core
    spec:
      containers:
      - name: cpp-core
        image: cpp-core:latest
        ports:
        - containerPort: 8012
---
apiVersion: v1
kind: Service
metadata:
  name: cpp-core
  labels:
    app: cpp-core
spec:
  selector:
    app: cpp-core
  ports:
  - name: port-8012
    port: 8012
    targetPort: 8012
    protocol: TCP
  type: ClusterIP
